package render

import "github.com/JongoDB-Labs/sre-v2/installer/internal/config"

// doNotEditLine is the shared footer marker reminding operators these files are
// generated; edit answers.yaml and re-render instead.
const doNotEditLine = "# Generated by srectl — edit answers.yaml and re-render rather than hand-editing."

// valuesOverlay is the structure of values.overlay.yaml — a Helm value overlay
// combining the sizing envelope and the posture hardening knobs.
type valuesOverlay struct {
	// Sizing echoes the tier for traceability.
	Sizing config.Sizing `yaml:"sizing"`
	// Posture echoes the profile for traceability.
	Posture config.Posture `yaml:"posture"`
	// Resources is the sizing-derived workload envelope.
	Resources resourcesSection `yaml:"resources"`
	// Postgres is the sizing-derived PGO instance/storage shape.
	Postgres postgresSection `yaml:"postgres"`
	// Security is the posture-derived hardening block.
	Security securitySection `yaml:"security"`
}

// resourcesSection is the replica count and per-pod requests/limits.
type resourcesSection struct {
	Replicas int            `yaml:"replicas"`
	Requests resourceBounds `yaml:"requests"`
	Limits   resourceBounds `yaml:"limits"`
}

// resourceBounds is a cpu/memory pair (Kubernetes quantity strings).
type resourceBounds struct {
	CPU    string `yaml:"cpu"`
	Memory string `yaml:"memory"`
}

// postgresSection is the PGO instance count and per-instance storage size.
type postgresSection struct {
	Instances   int    `yaml:"instances"`
	StorageSize string `yaml:"storageSize"`
}

// securitySection is the posture-driven hardening: FIPS, network policy, and the
// audit retention floor.
type securitySection struct {
	FIPS               bool   `yaml:"fips"`
	NetworkPolicy      string `yaml:"networkPolicy"`
	AuditRetentionDays int    `yaml:"auditRetentionDays"`
}

const valuesOverlayHeader = `# values.overlay.yaml — Helm value overlay for the SRE substrate.
# Rendered by srectl: sizing -> replicas/resources/PG instances/storage;
# posture -> fips/netpol/retention. Layer it with -f at install time.
#
` + doNotEditLine + "\n"

// renderValuesOverlay builds the values.overlay.yaml content from the answers.
func renderValuesOverlay(a config.Answers) (string, error) {
	res := ResourcesFor(a.Sizing)
	prof := ProfileFor(a.Posture)

	overlay := valuesOverlay{
		Sizing:  a.Sizing,
		Posture: a.Posture,
		Resources: resourcesSection{
			Replicas: res.Replicas,
			Requests: resourceBounds{CPU: res.CPURequest, Memory: res.MemoryRequest},
			Limits:   resourceBounds{CPU: res.CPULimit, Memory: res.MemoryLimit},
		},
		Postgres: postgresSection{
			Instances:   res.PGInstances,
			StorageSize: res.StorageSize,
		},
		Security: securitySection{
			FIPS:               prof.FIPS,
			NetworkPolicy:      prof.NetworkPolicy,
			AuditRetentionDays: prof.AuditRetentionDays,
		},
	}
	return marshalWithHeader(valuesOverlayHeader, overlay)
}
